=== ModelCheckingFramework/EFSM_Transformation_to_Anylogic/Source_Code/src/xml/editor/BaseComponentSchema.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Component">
    <xs:annotation>
      <xs:documentation>=========   Component ========</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element type="xs:long" name="Id"/>
        <xs:element type="xs:string" name="Name"/>
        <xs:element type="xs:string" name="Description"/>
        <xs:element name="InputVariable">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:long" name="Id"/>
              <xs:element type="xs:string" name="Name"/>
              <xs:element name="Properties">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute type="xs:string" name="Type"/>
                      <xs:attribute type="xs:byte" name="Value"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="OutputVariable">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:long" name="Id"/>
              <xs:element type="xs:string" name="Name"/>
              <xs:element name="Properties">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute type="xs:string" name="Type"/>
                      <xs:attribute type="xs:byte" name="Value"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="State" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:long" name="Id"/>
              <xs:element type="xs:string" name="Name"/>
              <xs:element type="xs:string" name="Initial"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="Transition" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:long" name="Id"/>
              <xs:element type="xs:string" name="Name"/>
              <xs:element name="Properties">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="Guard"/>
                    <xs:element type="xs:string" name="Event"/>
                    <xs:element type="xs:string" name="Action"/>
                    <xs:element name="TimeFunction">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute type="xs:string" name="Type" use="optional"/>
                            <xs:attribute type="xs:byte" name="Value" use="optional"/>
                            <xs:attribute type="xs:string" name="Unit" use="optional"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute type="xs:long" name="Source" use="optional"/>
                  <xs:attribute type="xs:long" name="Target" use="optional"/>
                  <xs:attribute type="xs:string" name="Type" use="optional"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== ModelCheckingFramework/EFSM_Transformation_to_Anylogic/Source_Code/src/xml/editor/BaseComponentDocument.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<Component
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='BaseComponentSchema.xsd'>
    <Id></Id>
    <Name></Name>
    <Description></Description>
    <InputVariable>
        <Id></Id>
        <Name></Name>
        <Properties Type="" Value=""></Properties>
    </InputVariable>
    <OutputVariable>
        <Id></Id>
        <Name></Name>
        <Properties Type="" Value=""></Properties>
    </OutputVariable>
    <State>
        <Id></Id>
        <Name></Name>
        <Initial></Initial>
    </State>
    <State>
        <Id></Id>
        <Name></Name>
        <Initial></Initial>
    </State>
    <State>
        <Id></Id>
        <Name></Name>
        <Initial></Initial>
    </State>
    <Transition>
        <Id></Id>
        <Name></Name>
        <Properties Source="" Target="" Type="">
            <Guard></Guard>
            <Event></Event>
            <Action></Action>
            <TimeFunction Type="" Value="" Unit=""></TimeFunction>
        </Properties>
    </Transition>
    <Transition>
        <Id></Id>
        <Name></Name>
        <Properties Source="" Target="" Type="">
            <Guard></Guard>
            <Event></Event>
            <Action></Action>
            <TimeFunction Type="" Value="" Unit=""></TimeFunction>
        </Properties>
    </Transition>
    <Transition>
        <Id></Id>
        <Name></Name>
        <Properties Source="" Target="" Type="">
            <Guard></Guard>
            <Event></Event>
            <Action></Action>
            <TimeFunction Type="" Value="" Unit=""></TimeFunction>
        </Properties>
    </Transition>

</Component>
